apiVersion: v2
name: role-provider-service
description: Zanzibar-based group and authorization service
type: application
version: 0.6.3-test.1
appVersion: "0.6.3-test.1"
maintainers:
  - name: Dennis Pfisterer
    email: dennis.pfisterer@dhbw.de
