---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "role-provider-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "role-provider-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-connection-string: {{ .Values.roleProviderService.db.connectionString | quote }}
  api-tokens: {{ .Values.roleProviderService.api.tokens | quote }}
